"""added price

Revision ID: 145550b19e3b
Revises: 4c359dd1051c
Create Date: 2023-03-26 20:48:44.627445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145550b19e3b'
down_revision = '4c359dd1051c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boat_times', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boat_times', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
