"""1 price

Revision ID: 5addad5f6de0
Revises: c30189820726
Create Date: 2023-03-28 17:18:26.184972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5addad5f6de0'
down_revision = 'c30189820726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boat_times', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.drop_column('weekday_price')
        batch_op.drop_column('weekend_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boat_times', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekend_price', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('weekday_price', sa.INTEGER(), nullable=True))
        batch_op.drop_column('price')

    # ### end Alembic commands ###
