"""jj

Revision ID: 5df5dd6e5e4b
Revises: d40f9db3ccdc
Create Date: 2023-03-30 09:53:03.989363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df5dd6e5e4b'
down_revision = 'd40f9db3ccdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boat_times', schema=None) as batch_op:
        batch_op.alter_column('reserved',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boat_times', schema=None) as batch_op:
        batch_op.alter_column('reserved',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
