"""wd

Revision ID: 7d95d27c3ee9
Revises: 145550b19e3b
Create Date: 2023-03-26 21:03:04.023666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d95d27c3ee9'
down_revision = '145550b19e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boat_times', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekday_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weekend_price', sa.Integer(), nullable=True))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boat_times', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.INTEGER(), nullable=False))
        batch_op.drop_column('weekend_price')
        batch_op.drop_column('weekday_price')

    # ### end Alembic commands ###
